# Generated by Django 3.2.4 on 2024-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('TEMP_MAX', 'TEMP_MAX'), ('TEMP_MIN', 'TEMP_MIN'), ('HUM_MAX', 'HUM_MAX'), ('HUM_MIN', 'HUM_MIN'), ('COUNTER_TRESHHOLD', 'COUNTER_TRESHHOLD')], max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parameters',
            },
        ),
    ]
