# Generated by Django 3.2.4 on 2024-12-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_incident', '0002_incidentnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentnote',
            old_name='closed_by',
            new_name='user_id',
        ),
    ]
