# Generated by Django 3.2.4 on 2024-12-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationsparameters_mainresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsparameters',
            name='mainResource',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='notificationsparameters',
            constraint=models.UniqueConstraint(fields=('type', 'mainResource'), name='unique_type_resource'),
        ),
    ]
